apiVersion: v1
kind: Namespace
metadata:
 name: ghost-blog
spec:
 finalizers:
 - kubernetes
---
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ghost-blog-deployment
  namespace: ghost-blog
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 1 
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3.42
        env:
        - name: NODE_ENV
          value: development   
        ports:
        - containerPort: 2368
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-blog-service
  namespace: ghost-blog
spec:
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
---
apiVersion: v1
kind: Service
metadata:
  name: ghost-blog-pod-service
  namespace: ghost-blog
spec:
  selector:
    app: ghost-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
  clusterIP: None  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-blog-ingress
  namespace: ghost-blog
  annotations:
    kubernetes.io/ingress.class: traefik
    #nginx.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/rule-type: Path
spec:
  rules:
  - #host: ghost.plogankonvoy.com   #without host name will use ELB or Custom domain and path routing
    http:
      paths:
      - path: /ghost
        pathType: Prefix
        backend:
          service:
            name: ghost-blog-service
            port:
              number: 80